### PR TITLE
Data from African trypanosome LOPIT

### PR DESCRIPTION
**Pull request by lmsimp**
- This PR adds 4 new LOPIT datasets generated from African trypanosomes
- Also in this PR I have updated the man pages to fix typos, missing characters and aliases as highlighted in build check

### CODE REVIEW

**Comment by lgatto** [comment]
Thank you for the PR @lmsimp. I won't have time to review it in depth right now, so feel free to merge or ask Olly if he wants to look at it too. Once merged, ping me and, if you don't have push rights to Bioc, I will push it. If that's the case, do make a request to get the necessary rights on Bioc, so I don't hold you up in the future.

**Review by lgatto — COMMENTED** [review]
I had a quick look and checked the Bioc version. Feel free to merge.

**Comment by lmsimp** [comment]
> Thank you for the PR @lmsimp. I won't have time to review it in depth right now, so feel free to merge or ask Olly if he wants to look at it too. Once merged, ping me and, if you don't have push rights to Bioc, I will push it. If that's the case, do make a request to get the necessary rights on Bioc, so I don't hold you up in the future.

Thanks Laurent. Please can you push to Bioc and I’ll email asking for push rights.

**Comment by lgatto** [comment]
done

**Pull request merged**
